using ApplicationCore.Interfaces.IServices;
using WkHtmlToPdfDotNet;
using WkHtmlToPdfDotNet.Contracts;
using IConverter = WkHtmlToPdfDotNet.Contracts.IConverter;

namespace Infrastructure.Implementations.Services
{
    public class HtmlToPdfService : IPdfService
    {
        private readonly IConverter _converter;

        public HtmlToPdfService(IConverter converter)
        {
            _converter = converter;
        }

        public byte[] ConvertHtmlToPdf(string html)
        {
            var doc = new HtmlToPdfDocument()
            {
                GlobalSettings = {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Portrait,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings() { Top = 10, Bottom = 10, Left = 10, Right = 10 },
                },
                Objects = {
                    new ObjectSettings()
                    {
                        PagesCount = true,
                        HtmlContent = html,
                        WebSettings = { DefaultEncoding = "utf-8" },
                        HeaderSettings = { FontSize = 9, Right = "Page [page] of [toPage]", Line = true },
                        FooterSettings = { FontSize = 9, Right = "Generated by Sola Web", Line = true }
                    }
                }
            };

            return _converter.Convert(doc);
        }
    }
}
